name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  server:
    name: Server Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache npm packages
        id: cache-npm-deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os}}-node-

      - name: Restore node_modules from cache
        id: restore-node-modules
        run: cd server && npm install

      - name: Run unit tests
        run: cd server && npm test
